### ISSUE TITLE
Support Client Example of React Native or Android SDK

### ISSUE THREAD

**Issue by makknife** [YubicoLabs/WebAuthnKit#17]
Hi,

I deployed the starter kit and all is working.
I accessed the Amplify endpoint with the React client on chrome using my laptop, and also my Android phone chrome browser. My yubikey bio works great.

I see that your iOS client is using the safari connector.
I was wondering if there is a wrapper to expose the Android SDK or yubikey Android SDK.
Can you provide a sample client example in this project or guidelines on this process?

I also looked at the Amplify API on React Native and unfortunately it looks like they don't have a passwordless configuration using a yubikey. I am okay with implementing the custom login flow and API calls, like in this project. I am just trying to find ways to not have to write in swift and java. I would like to approach deploying cross platform using expo react Native.

Thanks,
Kevin

**Comment by elukewalker** [comment]
Hi Kevin,

I'm glad everything is working well with your YubiKey Bio and the starter kit.

You are correct about the Amplify UI Authenticator component. I couldn't find a way to configure it for WebAuthn either. That is why we went the custom UI route.

The iOS client is intended to demonstrate how the SFSafariViewController enables the WebAuthn experience. The ASWebAuthenticationSession works as well.

 When it comes to native Android apps, Yubico does not currently offer a wrapper over the [FIDO2 API for Android](https://developers.google.com/identity/fido/android/native-apps). Nor does the [Yubico Mobile SDK for Android](https://github.com/Yubico/yubikit-android) currently include a FIDO2 module. The FIDO2 API for Android enables the built-in biometric to be used as a platform authenticator. Currently, cross-platform devices, such as YubiKeys, can be used with the CTAP1 flow.

We've taken your feature requests (1. React Native example, 2. Android client example) and put it on our backlog.

Be looking for a couple updates coming soon. We are focusing on the UX for the next release. Specifically, 

- guidelines to differentiate between Security Keys (cross-platform authenticators) and Trusted Devices (platform authenticators) 
- guidelines to utilize attestation to enhance the UI and security remediations

**Comment by makknife** [comment]
Thanks for the info!
